server:
  port: 7777
spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: 1227
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  main:
    lazy-initialization: true